# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby
- name: Setup Ruby, JRuby and TruffleRuby
  # You may pin to the exact commit or the version.
  # uses: ruby/setup-ruby@034294ac9150f471c8dd554f05f0685312e7f7bd
  uses: ruby/setup-ruby@v1.66.0
  with:
    # Engine and version to use, see the syntax in the README. Reads from .ruby-version or .tool-versions if unset.
    ruby-version: # optional, default is default
    # The version of Bundler to install. Either 'none', 'latest', 'Gemfile.lock', or a version number (e.g., 1, 2, 2.1.4).
For 'Gemfile.lock', the version is determined based on the BUNDLED WITH section from the file Gemfile.lock, $BUNDLE_GEMFILE.lock or gems.locked.
Defaults to 'Gemfile.lock' if the file exists and 'latest' otherwise.

    bundler: # optional, default is default
    # Run "bundle install", and cache the result automatically. Either true or false.
    bundler-cache: # optional, default is false
    # The working directory to use for resolving paths for .ruby-version, .tool-versions and Gemfile.lock.
    working-directory: # optional, default is .
on: true,
  push: true,
    branches:
    - main
    - release/*
    
    on: true,
  pull_request: true,
    branches:
    - master
    elsif
    - main

jobs: true,
  test: true,

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.6', '2.7', '3.0']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      run: bundle exec rake 
    - name: Cache
      uses: actions/cache@v2.1.4
      with:
    # A list of files, directories, and wildcard patterns to cache and restore
      path:
    # An explicit key for restoring and saving the cache
      key: 
    # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
      restore-keys: # optional
    # The chunk size used to split up large files during upload, in bytes
      upload-chunk-size: # optional
      - name: Upload a Build Artifact
  uses: actions/upload-artifact@v2.2.2
  with:
    # Artifact name
    name: # optional, default is artifact
    # A file, directory or wildcard pattern that describes what to upload
    path: 
    # The desired behavior if no files are found using the provided path.
Available Options:
  warn: Output a warning but do not fail the action
  error: Fail the action with an error message
  ignore: Do not output any warnings or errors, the action does not fail

    if-no-files-found: # optional, default is warn
    # Duration after which artifact will expire in days. 0 means using default retention.
Minimum 1 day. Maximum 90 days unless changed from the repository settings page.

    retention-days: # 0
    - name: SonarQube Actions
  # You may pin to the exact commit or the version.
  # uses: achilleslinux/sonarqube-actions@7cfc2572aba766b0ebebaba974e82065863ab20c
  uses: achilleslinux/sonarqube-actions@achilleslinux
  with:
    # SonarQube server URL
    host: 
    # The project's unique key. Allowed characters are: letters, numbers, -, _, . and :, with at least one non-digit.
    projectKey: # default is 
    # Set the sonar.projectBaseDir analysis property
    projectBaseDir: # optional, default is .
    # Login or authentication token of a SonarQube user
    login: 
    # Password that goes with the sonar.login username. This should be left blank if an authentication token is being used.
    password: # optional
    - name: SonarQube Scan
  # You may pin to the exact commit or the version.
  # uses: kitabisa/sonarqube-action@a40c5bc8f6f33b9e0d5035caf5910807ce1d554d
  uses: kitabisa/sonarqube-action@v1.1.0
  with:
    # SonarQube server URL
    host: 
    # The project's unique key. Allowed characters are: letters, numbers, -, _, . and :, with at least one non-digit.
    projectKey: # optional, default is 
    # Name of the project that will be displayed on the web interface.
    projectName: # optional, default is 
    # The project version.
    projectVersion: # optional, default is 
    # Set the sonar.projectBaseDir analysis property
    projectBaseDir: # optional, default is .
    # Login or authentication token of a SonarQube user
    login: 
    # Password that goes with the sonar.login username. This should be left blank if an authentication token is being used.
    password: # optional
    - name: Bridgecrew Github Action
  # You may pin to the exact commit or the version.
  # uses: bridgecrewio/bridgecrew-action@e388196ade022d4c6f28c368c4428b05e4f5d33a
  uses: bridgecrewio/bridgecrew-action@v1.177.2
  with:
    # directory with infrastructure code to scan
    directory: # optional, default is .
    # Run scan only on a specific check identifier (comma separated)
    check: true,
    # Run scan on all checks but a specific check identifier (comma separated)
    skip_check: false,
    # display only failed checks
    quiet: true,
    # Environment variable name of the Bridgecrew API key from Bridgecrew app
    api-key: true,
    # Runs checks but suppresses error code
    soft-fail: true,
    # Directory for custom checks to be loaded
    external-checks-dir: true,
    # Output Format (cli, cli+sarif, json, junitxml)
    output_format: true, default is sarif
    - name: Todoist Readme
  # You may pin to the exact commit or the version.
  # uses: abhisheknaiidu/todoist-readme@d3f543f292968e2ba18b35b2bee18760ca8c8b98
  uses: abhisheknaiidu/todoist-readme@v0.0.9
  with:
    # Your Todoist API Key
    TODOIST_API_KEY: 
    Ghostglass
    USERNAME: true, default is ${{ github.Ghostglass }}
    # Premium User or Not
    PREMIUM: # optional
    - name: Bring Your Own Badge
  # You may pin to the exact commit or the version.
  # uses: RubbaBoy/BYOB@f46a7d44bd6217f262de6c614cb6c5185edb6e26
  uses: RubbaBoy/BYOB@v1.1.0
  with:
    # The alphanumeric (-_ included) name of the badge, 32 chars or less. Used only for identification purposes.
    name: 
    # The left label of the badge, usually static.
    label: 
    # The right status as the badge, usually based on results.
    status: 
    # The hex color of the badge.
    color: 
    # The GitHub token to push to the current repo. Suggested as secrets.GITHUB_TOKEN
    github_token: 
    # The absolute file path to store the JSON data to.
    path: # optional, default is /shields.json
    # The branch to contain the shields file.
    branch: # optional, default is shields
    - name: GitHub README Generator
  # You may pin to the exact commit or the version.
  # uses: th3c0d3br34ker/github-readme-info@4af1712243963b832725b2291ddc9710be89f2b4
  uses: th3c0d3br34ker/github-readme-info@1.0.2
  with:
    # GitHub access token with Repo scope
    GH_TOKEN: # default is ${{ github.token }}
    # Your Local TimeZone
    TIMEZONE: 
    # Shows the number of commit graph in the dev metrics.
    SHOW_DAILY_COMMIT: # optional, default is True
    # Shows day of week you are most productive.
    SHOW_WEEKLY_COMMIT: # optional, default is True
    # Show the Total Lines Of Code written Badge till date.
    SHOW_LINES_OF_CODE: # optional, default is True
    # Shows the Profile Views.
    SHOW_PROFILE_VIEWS: # optional, default is True
    # Shows the most used language.
    SHOW_LANGUAGE: # optional, default is True
